- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: /bin/bash
    state: "{{ item.state | default('present') }}"
    group: "{{ item.group | default(omit) }}"


- name: Add SSH keys
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
    state: "{{ item.state | default('present') }}"
