- name: Setup users
  hosts: all
  become: true

  vars_files:
    - ../vars/example_users.yml

  tasks:
    - name: Create users and set SSH keys
      ansible.builtin.include_tasks:
        file: /home/service/AnsibleUserManagement/tasks/setup_users.yml

      loop: "{{ users }}"
