- name: Setup users
  hosts: all
  become: true

  vars_files:
    - ../vars/example_users.yml

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: /bin/bash
        state: "{{ item.state | default('present') }}"
      loop: "{{ users }}"
    
    - name: Add SSH keys
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        key: "{{ item.ssh_key }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ users }}"
